# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
target 'Etady' do

  use_frameworks!

  # Pods for Etady
  pod 'Alamofire', '~> 3.5.1'
  pod 'SwiftyJSON', '2.4.0'
  pod 'OAStackView'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Toast-Swift', '~> 1.4.0'  
  pod 'NVActivityIndicatorView', :git => 'https://github.com/ninjaprox/NVActivityIndicatorView.git', :branch => 'swift2.3'
  pod 'XLPagerTabStrip', '~> 5.0'
  pod 'SDWebImage'
#-------------------------------
target 'EtadyTests' do
    inherit! :search_paths

  end

target 'EtadyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
